//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVMB.Model
{
    using QLBVMB.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Booked : BaseViewModel
    {
        private string _Id_Booked;
        public string Id_Booked { get => _Id_Booked; set { _Id_Booked = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _Date;
        public Nullable<System.DateTime> Date { get => _Date; set { _Date = value; OnPropertyChanged(); } }

        private string _Id_Flight;
        public string Id_Flight { get => _Id_Flight; set { _Id_Flight = value; OnPropertyChanged(); } }

        private string _Id_Ticket;
        public string Id_Ticket { get => _Id_Ticket; set { _Id_Ticket = value; OnPropertyChanged(); } }

        private string _Id_Customer;
        public string Id_Customer { get => _Id_Customer; set { _Id_Customer = value; OnPropertyChanged(); } }

        private string _Id_CB;
        public string Id_CB { get => _Id_CB; set { _Id_CB = value; OnPropertyChanged(); } }

        private string _Id_AccountSeller;
        public string Id_AccountSeller { get => _Id_AccountSeller; set { _Id_AccountSeller = value; OnPropertyChanged(); } }

        public virtual Account Account { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Checked_Baggage Checked_Baggage { get; set; }
    }
}
