//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVMB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booked
    {
        public string Id_Booked { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Id_Flight { get; set; }
        public string Id_Ticket { get; set; }
        public string Id_Customer { get; set; }
        public string Id_CB { get; set; }
        public string Id_AccountSeller { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Checked_Baggage Checked_Baggage { get; set; }
    }
}
