//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVMB.Model
{
    using QLBVMB.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Booked : BaseViewModel
    {
        private string _Id_Booked;
        public string Id_Booked { get => _Id_Booked; set { _Id_Booked = value; OnPropertyChanged(); } }

        private string _Id_Flight;
        public string Id_Flight { get => _Id_Flight; set { _Id_Flight = value; OnPropertyChanged(); } }
   
        private Nullable<System.DateTime> _Date;
        public Nullable<System.DateTime> Date { get => _Date; set { _Date = value; OnPropertyChanged(); } }

        private string _Id_Ticket;
        public string Id_Ticket { get => _Id_Ticket; set { _Id_Ticket = value; OnPropertyChanged(); } }

        private string _Id_Customer;
        public string Id_Customer { get => _Id_Customer; set { _Id_Customer = value; OnPropertyChanged(); } }

        private string _Id_CB;
        public string Id_CB { get => _Id_CB; set { _Id_CB = value; OnPropertyChanged(); } }

        private string _Id_AccountSeller;
        public string Id_AccountSeller { get => _Id_AccountSeller; set { _Id_AccountSeller = value; OnPropertyChanged(); } }

        private Account _Account;
        public virtual Account Account { get => _Account; set { _Account = value; OnPropertyChanged(); } }

        private Flight _Flight;
        public virtual Flight Flight { get => _Flight; set { _Flight = value; OnPropertyChanged(); } }

        private Ticket _Ticket;
        public virtual Ticket Ticket { get => _Ticket; set { _Ticket = value; OnPropertyChanged(); } }

        private Customer _Customer;
        public virtual Customer Customer { get => _Customer; set { _Customer = value; OnPropertyChanged(); } }

        private Checked_Baggage _Checked_Baggage;
        public virtual Checked_Baggage Checked_Baggage { get => _Checked_Baggage; set { _Checked_Baggage = value; OnPropertyChanged(); } }
    }
}
