//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBVMB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Bookeds = new HashSet<Booked>();
        }
    
        public string Id_Customer { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Locate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booked> Bookeds { get; set; }
        public virtual Locate Locate1 { get; set; }
    }
}
